#
# Example:
#   cargo run --example read_flow_fairness_sim -- examples/read_flow_fairness_config.toml
#

[simulate]
duration = "70s"
report-path = "read-flow-fairness-sim.html"
yatp-threads = 2

[[payloads]]
name = "small"
concurrency = 4
rate = 20
query-concurrency = 2
query-cpu = "20ms"
query-task-slice-cpu = "2ms"
slow-query-latency = "60ms"

[[payloads]]
name = "large"
concurrency = 2
rate = 10
query-concurrency = 32
query-cpu = "200ms"
query-task-cpu = "20ms"
query-task-slice-cpu = "2ms"
start-time = "10s"
end-time = "60s"
#shared-flow-id = true
