#
# Example:
#   cargo run --example read_flow_fairness_sim -- examples/read_flow_fairness_config.toml
#

[simulate]
duration = "70s"
report-path = "read-flow-fairness-sim.html"
yatp-threads = 2
max-flow-concurrency = 128

[[payloads]]
name = "small"
concurrency = 4
rate = 20
query-concurrency = 2
query-cpu = "20ms"
query-task-slice-cpu = "1ms"
slow-query-latency = "60ms"

[[payloads]]
name = "large"
concurrency = 2
rate = 1
query-concurrency = 4
query-cpu = "10s"
query-task-cpu = "50ms"
query-task-slice-cpu = "1ms"
start-time = "10s"
end-time = "60s"
